// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE0zlaMrZYptGQX9hkgvibmpjSI-kXzdk',
    appId: '1:807549497379:web:49efb68f9889a941cb0196',
    messagingSenderId: '807549497379',
    projectId: 'prueba-01-1cc15',
    authDomain: 'prueba-01-1cc15.firebaseapp.com',
    databaseURL: 'https://prueba-01-1cc15-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-01-1cc15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3SM6dNFyTmCvf7wzQuUJXnLOMurWruEE',
    appId: '1:807549497379:android:26516e6f75e4371ccb0196',
    messagingSenderId: '807549497379',
    projectId: 'prueba-01-1cc15',
    databaseURL: 'https://prueba-01-1cc15-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-01-1cc15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgdTArLtLE_ZTP_A2veKrH3SrG2Loe2RY',
    appId: '1:807549497379:ios:72b52a035bf73ec0cb0196',
    messagingSenderId: '807549497379',
    projectId: 'prueba-01-1cc15',
    databaseURL: 'https://prueba-01-1cc15-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-01-1cc15.appspot.com',
    iosBundleId: 'com.example.prueba01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgdTArLtLE_ZTP_A2veKrH3SrG2Loe2RY',
    appId: '1:807549497379:ios:72b52a035bf73ec0cb0196',
    messagingSenderId: '807549497379',
    projectId: 'prueba-01-1cc15',
    databaseURL: 'https://prueba-01-1cc15-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-01-1cc15.appspot.com',
    iosBundleId: 'com.example.prueba01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE0zlaMrZYptGQX9hkgvibmpjSI-kXzdk',
    appId: '1:807549497379:web:eb44b791d02b5973cb0196',
    messagingSenderId: '807549497379',
    projectId: 'prueba-01-1cc15',
    authDomain: 'prueba-01-1cc15.firebaseapp.com',
    databaseURL: 'https://prueba-01-1cc15-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-01-1cc15.appspot.com',
  );

}